name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Prettier"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::Install"
          npm install prettier
          echo "::endgroup::"
          npx prettier --check .

      - name: "Yamllint"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::List Files"
          yamllint --list-files .
          echo "::endgroup::"
          yamllint .

      - name: "Actionlint"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::Download"
          loc=$(curl -sI https://github.com/rhysd/actionlint/releases/latest | grep -i '^location:')
          echo "loc: ${loc}"
          tag=$(echo "${loc}" | sed -E 's|.*/tag/v?(.*)|\1|' | tr -d '\t\r\n')
          echo "tag: ${tag}"
          url="https://github.com/rhysd/actionlint/releases/latest/download/actionlint_${tag}_linux_amd64.tar.gz"
          echo "url: ${url}"
          curl -sL "${url}" | tar xz -C "${RUNNER_TEMP}" actionlint
          file "${RUNNER_TEMP}/actionlint"
          "${RUNNER_TEMP}/actionlint" --version
          echo "::endgroup::"
          "${RUNNER_TEMP}/actionlint" -color -verbose -shellcheck= -pyflakes=
