name: "NPM Build"

on:
  workflow_call:
    inputs:
      install:
        type: string
        default: "npm ci"
      build:
        type: string
        default: "npm run build"
      path:
        type: string
        default: "dist"
      name:
        type: string
        default: "artifact"
      pages:
        type: boolean
        default: false
    secrets:
      webhook:
      DISCORD_WEBHOOK:
      ai_chat_api:
      AI_CHAT_API:
      ai_chat_auth:
      AI_CHAT_AUTH:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Install"
        run: |
          ${{ inputs.install }}

      - name: "Build"
        env:
          VITE_AI_API: ${{ secrets.AI_CHAT_API || secrets.ai_chat_api }}
          VITE_AI_AUTH: ${{ secrets.AI_CHAT_AUTH || secrets.ai_chat_auth }}
        run: |
          ${{ inputs.build }}

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "inputs.name: ${{ inputs.name }}"
          echo "inputs.path: ${{ inputs.path }}"
          echo "::group::ls"
          ls -lAh .
          echo "::endgroup::"
          ls -lAh ${{ inputs.path }}
          echo "::group::tree"
          tree ${{ inputs.path }}
          echo "::endgroup::"

      - name: "Upload Artifact"
        if: ${{ !inputs.pages }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          if-no-files-found: "error"
          include-hidden-files: true

      - name: "Upload Pages Artifact"
        if: ${{ inputs.pages }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ inputs.path }}

      - name: "Send Discord Notification"
        if: ${{ failure() && env.webhook }}
        uses: sarisia/actions-status-discord@v1
        env:
          webhook: ${{ secrets.DISCORD_WEBHOOK || secrets.webhook }}
        with:
          webhook: ${{ env.webhook }}
          description: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
